-- ═════════════════════════════════════════════════════════════════════════════
-- ADIIITECH_ SUPABASE DATABASE SCHEMA
-- Copy and paste this into Supabase SQL Editor and click "RUN"
-- ═════════════════════════════════════════════════════════════════════════════

-- 1. APPS TABLE
CREATE TABLE IF NOT EXISTS public.apps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    version TEXT DEFAULT 'MOD',
    size TEXT DEFAULT '—',
    features JSONB DEFAULT '[]'::jsonb,
    download_url TEXT DEFAULT '#',
    color_from TEXT DEFAULT '#b44dff',
    color_to TEXT DEFAULT '#191414',
    glow_color TEXT DEFAULT 'purple',
    safe BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TIPS TABLE
CREATE TABLE IF NOT EXISTS public.tips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT DEFAULT 'android',
    tag TEXT DEFAULT '⚡ Trick',
    description TEXT,
    read_more_url TEXT DEFAULT '#',
    icon_color TEXT DEFAULT '#00f5ff',
    glow_color TEXT DEFAULT 'purple',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. RESOURCES TABLE
CREATE TABLE IF NOT EXISTS public.resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    type TEXT DEFAULT 'PDF Guide',
    type_emoji TEXT DEFAULT '📄',
    description TEXT,
    download_url TEXT DEFAULT '#',
    icon_color TEXT DEFAULT 'purple',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. SITE SETTINGS & CREDENTIALS TABLE
CREATE TABLE IF NOT EXISTS public.settings (
    id TEXT PRIMARY KEY DEFAULT 'site_config',
    tagline TEXT DEFAULT 'Your Hub for Tech Tricks, Mods & Resources',
    about_text1 TEXT DEFAULT 'Main ek tech influencer hun jo apni audience ko real, kaam aane wali cheezein deta hai — koi bakwaas nahi, sirf value. Modded apps se leke hidden tricks tak, main sab share karta hun bilkul free mein.',
    about_text2 TEXT DEFAULT 'Mera mission hai ki tech ko sab ke liye accessible banana — chaahe aapka phone purana ho ya naya, aapko best experience milna chahiye.',
    stat_followers INT DEFAULT 50,
    stat_apps INT DEFAULT 200,
    stat_tips INT DEFAULT 500,
    social JSONB DEFAULT '{"telegram":"#","instagram":"#","youtube":"#","whatsapp":"#"}'::jsonb,
    admin_email TEXT DEFAULT 'collab.ahad@gmail.com',
    admin_password TEXT DEFAULT 'adiiitech2025',
    collab_phone TEXT DEFAULT '+919012786022',
    collab_whatsapp TEXT DEFAULT '919012786022',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. BRANDS TABLE (FOR COLLABORATIONS)
CREATE TABLE IF NOT EXISTS public.brands (
    id TEXT PRIMARY KEY,
    brand_name TEXT NOT NULL,
    contact_person TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    website TEXT DEFAULT '',
    collab_type TEXT DEFAULT 'Paid', -- 'Paid' or 'Barter'
    budget TEXT DEFAULT '',
    campaign_type TEXT DEFAULT 'Reel / Short Video',
    initial_message TEXT DEFAULT '',
    status TEXT DEFAULT 'New', -- 'New', 'In Discussion', 'Deal Closed', 'Declined'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. BRAND MESSAGES TABLE (2-WAY CHAT & ATTACHMENTS)
CREATE TABLE IF NOT EXISTS public.brand_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id TEXT REFERENCES public.brands(id) ON DELETE CASCADE,
    sender TEXT NOT NULL, -- 'brand' or 'admin'
    message TEXT DEFAULT '',
    attachment_url TEXT DEFAULT NULL,
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ═════════════════════════════════════════════════════════════════════════════
-- ENABLE ROW LEVEL SECURITY & ALLOW PUBLIC READ / WRITE
-- ═════════════════════════════════════════════════════════════════════════════
ALTER TABLE public.apps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tips ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brand_messages ENABLE ROW LEVEL SECURITY;

-- Allow public read & write policies for client
DROP POLICY IF EXISTS "Public Read Apps" ON public.apps;
CREATE POLICY "Public Read Apps" ON public.apps FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read Tips" ON public.tips;
CREATE POLICY "Public Read Tips" ON public.tips FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read Resources" ON public.resources;
CREATE POLICY "Public Read Resources" ON public.resources FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read Settings" ON public.settings;
CREATE POLICY "Public Read Settings" ON public.settings FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read Brands" ON public.brands;
CREATE POLICY "Public Read Brands" ON public.brands FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Read Brand Messages" ON public.brand_messages;
CREATE POLICY "Public Read Brand Messages" ON public.brand_messages FOR ALL USING (true) WITH CHECK (true);

-- ═════════════════════════════════════════════════════════════════════════════
-- INITIAL DEFAULT DATA SEEDING
-- ═════════════════════════════════════════════════════════════════════════════
INSERT INTO public.settings (id, tagline, stat_followers, stat_apps, stat_tips, admin_email, admin_password, collab_phone, collab_whatsapp)
VALUES ('site_config', 'Your Hub for Tech Tricks, Mods & Resources', 50, 200, 500, 'collab.ahad@gmail.com', 'adiiitech2025', '+919012786022', '919012786022')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.apps (name, version, size, features, download_url, color_from, color_to, glow_color, safe)
VALUES 
('Spotify Premium', 'v9.0.2 MOD', '42 MB', '["No Ads", "Offline", "Unlimited Skips"]'::jsonb, '#', '#1db954', '#191414', 'purple', true),
('YouTube Premium', 'v19.45 MOD', '78 MB', '["No Ads", "Background Play", "Picture-in-Picture"]'::jsonb, '#', '#ff0000', '#8b0000', 'red', true),
('Netflix MOD', 'v8.119 MOD', '56 MB', '["Premium Unlocked", "4K Stream", "Download Videos"]'::jsonb, '#', '#e50914', '#141414', 'cyan', true),
('Canva Pro', 'v2.265 MOD', '95 MB', '["Pro Unlocked", "All Templates", "No Watermark"]'::jsonb, '#', '#7d2ae8', '#00c4cc', 'green', true),
('Instagram MOD', 'v350.0 MOD', '68 MB', '["Story Downloader", "No Ads", "Ghost Mode"]'::jsonb, '#', '#f09433', '#bc1888', 'purple', true),
('CapCut Pro', 'v13.5 MOD', '112 MB', '["All Effects", "No Watermark", "Pro Filters"]'::jsonb, '#', '#000000', '#333333', 'cyan', true)
ON CONFLICT DO NOTHING;

INSERT INTO public.tips (title, category, tag, description, read_more_url, icon_color, glow_color)
VALUES
('Battery Life 3x Karo Bina Kisi App Ke', 'android', '⚡ Battery', 'Ye hidden Android settings ON karo aur battery drain almost band ho jayegi. Developer options ka ek secret trick.', '#', '#39ff14', 'purple'),
('Screen Recording Bina Watermark — 100% Free', 'android', '🎥 Recording', 'Koi bhi paid app ki zarurat nahi. Ye native trick se HD screen recording karo without any watermark.', '#', '#00f5ff', 'cyan'),
('Windows 11 Speed Boost — 10 Secret Settings', 'pc', '💻 Windows', 'Purana lagta tha PC? Ye 10 registry tweaks aur settings se aapka Windows rocket ban jayega.', '#', '#b44dff', 'green'),
('BGMI / PUBG Lag Fix — 60 FPS Guaranteed', 'gaming', '🎮 Gaming', 'Low-end phone pe bhi 60 FPS milega. Ye settings aur config file se game bilkul smooth ho jayegi.', '#', '#39ff14', 'purple'),
('iPhone Hidden Features jo Apple Nahi Batata', 'iphone', '🍎 iOS', '5 aise features jo iOS mein already hain lekin 99% log nahi jaante. Aaj se use karo!', '#', '#00f5ff', 'cyan'),
('Phone Ko Hack Hone Se Kaise Bachao', 'android', '🔐 Security', 'Ye 7 security settings aaj hi ON karo. Aapka data aur privacy 100% safe rahega hackers se.', '#', '#39ff14', 'green')
ON CONFLICT DO NOTHING;

INSERT INTO public.resources (title, type, type_emoji, description, download_url, icon_color)
VALUES
('Complete Android Root Guide 2025', 'PDF Guide', '📄', 'Step-by-step guide har Android phone ke liye. Beginner-friendly.', '#', 'purple'),
('VPN Collection — 50+ Premium Configs', 'Premium Tool', '⭐', 'Working VPN configs jo kabhi ban nahi hote. Monthly update hota hai.', '#', 'cyan'),
('BGMI / Free Fire Sensitivity Settings', 'Cheat Sheet', '📋', 'Pro players ki exact sensitivity settings aur configs. Copy paste karo aur win karo.', '#', 'green'),
('PC Optimization Tool Pack', 'Tool Kit', '🔧', '7 best free tools jo aapka Windows PC turbo-charge kar denge. No bloatware.', '#', 'purple')
ON CONFLICT DO NOTHING;
